steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/${CI_REPO_NAME%%-service}
      tags: latest
      platforms: linux/amd64
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  # all events except pull_request
  - event: [push, pull_request_closed, tag, release, deployment, cron, manual]
    branch: master
