steps:
  build-and-push-tag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/${CI_REPO_NAME%-service}
      tags: ${CI_COMMIT_TAG##v}
      platforms: linux/amd64
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  - event: tag
